version: '3'

x-common:
  &common
  build:
    dockerfile: Dockerfile
  env_file: '.env'
  restart: on-failure

services:
  lightspeed-ingest:
    container_name: lightspeed-ingest
    # image: projectlightspeed/ingest
    image: lightspeed-ingest
    build:
      context: ./ingest
    ports:
      - "${INGEST_PORT}:8084"
    <<: *common

  lightspeed-react:
    container_name: lightspeed-react
    # image: projectlightspeed/react
    image: lightspeed-react
    build:
      context: ./frontend
    ports:
      - "${WEB_PORT}:80"
    <<: *common

  lightspeed-webrtc:
    container_name: lightspeed-webrtc
    # image: projectlightspeed/webrtc
    image: lightspeed-webrtc
    build:
      context: ./webrtc
    command:
      [
        "lightspeed-webrtc",
        "--addr=0.0.0.0",
        "--ip=${WEB_HOST}",
        "--ports=20000-20100",
        "run"
      ]
    ports:
      - ${WEBSOCKET_PORT}:8080 # WebRTC
      - 65535:65535/udp # RTP
      - 20000-20100:20000-20100/tcp # WebRTC PeerConnection
      - 20000-20100:20000-20100/udp # WebRTC PeerConnection UDP
    <<: *common

  lightspeed-main:
    container_name: lightspeed-main
    image: lightspeed-main
    build:
      context: ./main
    ports:
      - 80:8090/tcp
    <<: *common
